# Generated by Django 3.2.18 on 2023-03-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20230313_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['created_on_note']},
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='projects.post'),
        ),
    ]
