# Generated by Django 3.2.18 on 2023-03-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20230318_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
