# Generated by Django 3.2.18 on 2023-03-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_post_excerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='description',
        ),
    ]
