# Generated by Django 3.2.18 on 2023-04-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
