# Generated by Django 3.2.18 on 2023-04-07 14:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_post_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
