# Generated by Django 3.2.18 on 2023-04-07 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_remove_profile_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_on_feedback',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
