# Generated by Django 3.2.18 on 2023-04-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_request_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
    ]
