# Generated by Django 3.2.18 on 2023-04-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_remove_post_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_on_note']},
        ),
    ]
