# Generated by Django 3.2.18 on 2023-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20230413_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_color',
            field=models.CharField(blank=True, default='#ffd041', max_length=7, null=True),
        ),
    ]
