# Generated by Django 3.2.18 on 2023-04-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_profile_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_days',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
