# Generated by Django 3.2.18 on 2023-04-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_alter_profile_active_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='public_email',
        ),
    ]
