# Generated by Django 3.2.18 on 2023-04-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_alter_profile_profile_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_quote',
            field=models.CharField(blank=True, default='N/A', max_length=84, null=True),
        ),
    ]
