# Generated by Django 3.2.18 on 2023-04-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_alter_profile_profile_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
    ]
