# Generated by Django 3.2.18 on 2023-04-17 20:55

import cloudinary_storage.storage
import cloudinary_storage.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_alter_profile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_video',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='user-videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'zip'])]),
        ),
    ]
