# Generated by Django 3.2.18 on 2023-04-17 21:11

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20230417_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='user-videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
