# Generated by Django 3.2.18 on 2023-04-17 21:53

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_alter_profile_user_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bigger_fish_results',
            field=models.ImageField(blank=True, max_length=84, null=True, upload_to='bigger_fish_results/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_routine',
            field=models.FileField(blank=True, max_length=84, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='daily_routine/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'xlsm', 'xlsb', 'csv', 'parquet'])]),
        ),
    ]
