# Generated by Django 3.2.18 on 2023-04-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20230417_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='articles',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='awards',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_rewards',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='certificates',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='change',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contribution',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='future',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goals',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goals_completed',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='honors',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ideal_life',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='innovation_land_rewards',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests_hobbies_wall',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='journey',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='knowledge',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='legacy',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='milestones_completed',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='missions_completed',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='motivation_wall',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects_completed',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recognition',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recommendations',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='references',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='results',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='story',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='strengths',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tasks_completed',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weaknesses',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_history',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
    ]
