# Generated by Django 3.2.18 on 2023-05-01 21:12

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20230425_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projects_portfolio',
            field=models.FileField(blank=True, max_length=210, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='portfolios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'zip'])]),
        ),
    ]
