# Generated by Django 3.2.18 on 2023-05-01 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20230501_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_audio',
            field=models.FileField(blank=True, null=True, upload_to='profile_audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])]),
        ),
    ]
