# Generated by Django 3.2.18 on 2023-05-01 22:52

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_alter_profile_profile_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_audio',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='profile_audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])]),
        ),
    ]
