# Generated by Django 3.2.18 on 2023-05-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_auto_20230502_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_color',
            field=models.CharField(blank=True, default='#ffc107', max_length=7, null=True),
        ),
    ]
