# Generated by Django 3.2.18 on 2023-05-12 09:56

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[projects.models.Profile.validate_file_name_length, projects.models.Profile.max_file_size_ten]),
        ),
    ]
