# Generated by Django 3.2.18 on 2023-05-13 16:41

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_auto_20230513_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bigger_fish_results_extension',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bigger_fish_results',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='bigger_fish_results/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), projects.models.Profile.validate_file_name_length, projects.models.Profile.max_file_size_ten]),
        ),
    ]
