# Generated by Django 3.2.18 on 2023-05-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20230513_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
