# Generated by Django 3.2.18 on 2023-05-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_remove_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10, null=True),
        ),
    ]
