# Generated by Django 3.2.18 on 2023-05-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='articles',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='awards',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_rewards',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='certificates',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='change',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contribution',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='future',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goals',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goals_completed',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='honors',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='innovation_land_rewards',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='journey',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='knowledge',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='legacy',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='milestones_completed',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='missions_completed',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects_completed',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recognition',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recommendations',
            field=models.TextField(blank=True, max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='references',
            field=models.TextField(blank=True, max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='results',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='strengths',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tasks_completed',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weaknesses',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
    ]
