# Generated by Django 3.2.18 on 2023-05-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_alter_profile_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
