# Generated by Django 3.2.18 on 2023-05-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_remove_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Human', 'Human'), ('AI', 'AI')], max_length=5, null=True),
        ),
    ]
