# Generated by Django 3.2.18 on 2023-06-13 10:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0074_auto_20230612_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amount_asked',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AddField(
            model_name='post',
            name='event_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AddField(
            model_name='post',
            name='event_color',
            field=models.CharField(blank=True, default='#ffc107', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_content',
            field=models.TextField(blank=True, max_length=420, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_host',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_event_images/', validators=[projects.models.Post.validate_file_name_length, projects.models.Post.max_file_size_ten]),
        ),
        migrations.AddField(
            model_name='post',
            name='event_link',
            field=models.URLField(blank=True, max_length=210, null=True, verbose_name='Event URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='event_location',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='event_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AddField(
            model_name='post',
            name='event_price_cents',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='post',
            name='event_title',
            field=models.CharField(blank=True, max_length=84, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_phases',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='post',
            name='ownerhip_given',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='ownership_offered',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='public_phone',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rspv_maybe',
            field=models.ManyToManyField(blank=True, related_name='rspv_maybe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='rspv_next_time',
            field=models.ManyToManyField(blank=True, related_name='rspv_next_time', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='rspv_no',
            field=models.ManyToManyField(blank=True, related_name='rspv_no', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='rspv_yes',
            field=models.ManyToManyField(blank=True, related_name='rspv_yes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='team_positions_given',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21042004)]),
        ),
        migrations.AddField(
            model_name='post',
            name='team_positions_offered',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21042004)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_on_note',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='amount_collected',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='stocks_offering',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hours_per_week',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_on_request',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
