# Generated by Django 3.2.18 on 2023-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_auto_20230613_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
