# Generated by Django 3.2.18 on 2023-06-13 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_note_note_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_hour',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='post',
            name='event_minute',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
