# Generated by Django 3.2.18 on 2023-06-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0077_auto_20230613_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
