# Generated by Django 3.2.18 on 2023-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_auto_20230619_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_colors_list',
            field=models.BooleanField(default=False),
        ),
    ]
