# Generated by Django 3.2.18 on 2023-06-19 13:47

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_post_post_colors_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_bridge_privacy',
            new_name='event_privacy',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='public_visibility',
            new_name='post_bridge_privacy_documents',
        ),
        migrations.AddField(
            model_name='post',
            name='capabilities',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='capabilities/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'zip']), projects.models.Post.validate_file_name_length, projects.models.Post.max_file_size_ten]),
        ),
        migrations.AddField(
            model_name='post',
            name='post_bridge_privacy_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='public_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
