# Generated by Django 3.2.18 on 2023-06-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_post_post_color_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
