# Generated by Django 3.2.18 on 2023-06-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0083_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='organization',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_location_city',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_location_continent',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_location_country',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_location_planet',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='post',
            name='project',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='post',
            name='project_owner',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='post',
            name='service',
            field=models.CharField(max_length=21),
        ),
    ]
