# Generated by Django 3.2.18 on 2023-06-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_auto_20230620_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='industry',
            field=models.CharField(max_length=21),
        ),
    ]
