# Generated by Django 3.2.18 on 2023-06-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0087_post_post_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_author_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_logo_image',
        ),
    ]
