# Generated by Django 3.2.18 on 2023-06-21 10:46

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_auto_20230621_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_logo_images/', validators=[projects.models.Post.validate_file_name_length, projects.models.Post.max_file_size_ten]),
        ),
    ]
