# Generated by Django 3.2.18 on 2023-06-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0092_remove_post_author_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_location_city',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_location_country',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Organization', 'Organization'), ('Project', 'Project'), ('Product', 'Product'), ('Service', 'Service')], max_length=12, null=True),
        ),
    ]
