# Generated by Django 3.2.18 on 2023-06-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_auto_20230621_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_location_continent',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_location_planet',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
