# Generated by Django 3.2.18 on 2023-06-22 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_post_author_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='same_start_launch_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
