# Generated by Django 3.2.18 on 2023-06-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0096_auto_20230622_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, max_length=420, null=True),
        ),
    ]
