# Generated by Django 3.2.18 on 2023-06-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_alter_post_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='franchizing',
            new_name='ecosystem_relationship',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='intellectual_property',
            new_name='franchizing_licencing',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='licencing',
            new_name='target_groups',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pps_milestones',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pps_objectives',
        ),
        migrations.RemoveField(
            model_name='post',
            name='target_group',
        ),
        migrations.AddField(
            model_name='post',
            name='pps_missions',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pps_planner',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pps_vision',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='challenges',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='change',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='impact',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='organization_info',
            field=models.TextField(blank=True, max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pps_goals',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='risks',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
    ]
