# Generated by Django 3.2.18 on 2023-06-24 23:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0098_auto_20230624_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='amount_requested',
            new_name='end_product_or_service_total_supply',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='end_date',
            new_name='funding_end_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='community_access',
            new_name='funding_infinite_end_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='payout_date',
            new_name='funding_payout_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='start_date',
            new_name='funding_start_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='infinite_end_date',
            new_name='introduction_privacy',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='open_offers',
            new_name='launch_date_privacy',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='lifetime_discount_percentages',
            new_name='lifetime_discount_percentages_quantity_proposal',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ownership_percentage',
            new_name='ownership_percentage_opps_quantity_proposal',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pioneering',
            new_name='percentage_special_privacy',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_bridge_privacy_documents',
            new_name='post_bridge_privacy_cabinet',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_conclusion_privacy',
            new_name='post_opps_details_privacy',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_fee_model_privacy',
            new_name='post_proposal_model_privacy',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='stocks_offering',
            new_name='stocks_quantity_proposal',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='end_product_or_service_quantity',
            new_name='stocks_quantity_total_supply',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collaboration',
        ),
        migrations.RemoveField(
            model_name='post',
            name='end_product_or_service_quality',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fee_model',
        ),
        migrations.RemoveField(
            model_name='post',
            name='merchandize',
        ),
        migrations.RemoveField(
            model_name='post',
            name='offer_model',
        ),
        migrations.RemoveField(
            model_name='post',
            name='offer_terms',
        ),
        migrations.RemoveField(
            model_name='post',
            name='partnership',
        ),
        migrations.RemoveField(
            model_name='post',
            name='return_amount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='special_acknowledgement',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sponsorship',
        ),
        migrations.RemoveField(
            model_name='post',
            name='stocks_supply',
        ),
        migrations.RemoveField(
            model_name='post',
            name='team_guaranteed_position',
        ),
        migrations.RemoveField(
            model_name='post',
            name='timeline',
        ),
        migrations.AddField(
            model_name='post',
            name='collaboration_proposal',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='collaboration_proposal_return',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='end_product_or_service_membership_proposal',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='end_product_or_service_merch_proposal',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='end_product_or_service_proposal_note',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='end_product_or_service_proposal_return',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='end_product_or_service_quantity_proposal',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999999), projects.models.Post.validate_end_ps_proposal]),
        ),
        migrations.AddField(
            model_name='post',
            name='end_product_or_service_type',
            field=models.CharField(blank=True, choices=[('Product', 'Product'), ('Service', 'Service'), ('Both', 'Both')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lifetime_discount_percentages_proposal_return',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lifetime_discount_percentages_quality_proposal_note',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='open_proposal',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='open_proposal_proposal_return',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ownership_percentage_opps_proposal_note',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ownership_percentage_opps_proposal_return',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ownership_percentage_opps_type',
            field=models.CharField(blank=True, choices=[('Organization', 'Organization'), ('Project', 'Project'), ('Product', 'Product'), ('Service', 'Service'), ('Combination', 'Combination')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='partnership_proposal',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='partnership_proposal_return',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_finance',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_finance_two',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_hr',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_hr_two',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_marketing',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_marketing_two',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_ops',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_ops_two',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_research',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_research_two',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_supply_chain',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_supply_chain_two',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_sustainability',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_sustainability_two',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_tech',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='percentage_special_tech_two',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='proposal_terms_and_conditions',
            field=models.TextField(blank=True, max_length=840, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sponsorship_proposal',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sponsorship_proposal_return',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='stocks_proposal_note',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='stocks_proposal_return',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='team_guaranteed_employment_conditions_proposal',
            field=models.TextField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='team_guaranteed_position_title_proposal',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='team_guaranteed_proposal_return',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='team_guaranteed_responsibilities_proposal',
            field=models.TextField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_type',
            field=models.CharField(choices=[('Human', 'Human'), ('A.I.', 'A.I.')], default='any', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='business_knowledge',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, default='any', max_length=420),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='launch_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_content',
            field=models.TextField(blank=True, max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='opportunities',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='organization',
            field=models.CharField(blank=True, max_length=21),
        ),
        migrations.AlterField(
            model_name='post',
            name='organization_culture',
            field=models.TextField(blank=True, max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_color_primary',
            field=models.CharField(default='#292b2c', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_color_secondary',
            field=models.CharField(default='#ffc107', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_color_text',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_list_description',
            field=models.CharField(max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_location_city',
            field=models.CharField(default='any', max_length=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_location_continent',
            field=models.CharField(default='any', max_length=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_location_country',
            field=models.CharField(default='any', max_length=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_location_planet',
            field=models.CharField(default='any', max_length=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Organization', 'Organization'), ('Project', 'Project'), ('Product', 'Product'), ('Service', 'Service')], default='any', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.CharField(blank=True, max_length=21),
        ),
        migrations.AlterField(
            model_name='post',
            name='project',
            field=models.CharField(blank=True, max_length=21),
        ),
        migrations.AlterField(
            model_name='post',
            name='project_owner',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='service',
            field=models.CharField(blank=True, max_length=21),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_finance',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_finance_two',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_hr',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_hr_two',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_marketing',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_marketing_two',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_ops',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_ops_two',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_research',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_research_two',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_supply_chain',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_supply_chain_two',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_sustainability',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_sustainability_two',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_tech',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_tech_two',
            field=models.TextField(blank=True, max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='strengths',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='threats',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(related_name='projects_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='weaknesses',
            field=models.TextField(blank=True, max_length=168, null=True),
        ),
    ]
