# Generated by Django 3.2.18 on 2023-06-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0100_auto_20230624_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_public_email',
            new_name='public_email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='amount_asked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='amount_collected',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_capacity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_host',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_hour',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_minute',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_price_cents',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_privacy',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='number_of_phases',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ownerhip_given',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ownership_offered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_results_privacy',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rspv_maybe',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rspv_next_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rspv_no',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rspv_yes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='team_positions_given',
        ),
        migrations.RemoveField(
            model_name='post',
            name='team_positions_offered',
        ),
        migrations.AlterField(
            model_name='post',
            name='contact_days',
            field=models.TextField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact_hours',
            field=models.TextField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='organization_mission',
            field=models.TextField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='organization_vision',
            field=models.TextField(blank=True, max_length=42, null=True),
        ),
    ]
