# Generated by Django 3.2.18 on 2023-06-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_auto_20230625_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_color_primary',
            field=models.CharField(default='#292b2c', max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='post_color_secondary',
            field=models.CharField(default='#ffc107', max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='post_color_text',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='post_colors_list',
            field=models.BooleanField(default=False),
        ),
    ]
