# Generated by Django 3.2.18 on 2023-06-26 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0105_auto_20230626_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='launch_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
