# Generated by Django 3.2.18 on 2023-06-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0107_auto_20230628_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='collaboration_proposal',
            new_name='collaboration_proposal_costs',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='open_proposal',
            new_name='open_proposal_costs',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='partnership_proposal',
            new_name='partnership_proposal_costs',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sponsorship_proposal',
            new_name='sponsorship_proposal_costs',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='team_guaranteed_proposal_return',
            new_name='team_guaranteed_proposal_costs',
        ),
        migrations.RemoveField(
            model_name='post',
            name='end_product_or_service_proposal_note',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lifetime_discount_percentages_quality_proposal_note',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ownership_percentage_opps_proposal_note',
        ),
        migrations.RemoveField(
            model_name='post',
            name='stocks_proposal_note',
        ),
        migrations.AddField(
            model_name='post',
            name='end_product_or_service_proposal_costs',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lifetime_discount_percentages_quality_proposal_costs',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ownership_percentage_opps_proposal_costs',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='stocks_proposal_costs',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_product_or_service_membership_proposal',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_product_or_service_merch_proposal',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='team_guaranteed_employment_conditions_proposal',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='team_guaranteed_position_title_proposal',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='team_guaranteed_responsibilities_proposal',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
    ]
