# Generated by Django 3.2.18 on 2023-07-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0112_auto_20230704_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_colors_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_color_primary',
            field=models.CharField(default='#CFF4FC', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_color_secondary',
            field=models.CharField(default='#F2F3F5', max_length=7),
        ),
    ]
