# Generated by Django 3.2.18 on 2023-07-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0114_rename_current_employment_privacy_profile_occupation_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='history_employment_privacy',
            new_name='career_privacy',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cv',
            new_name='employment_history',
        ),
    ]
