# Generated by Django 3.2.18 on 2023-07-08 10:09

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0115_auto_20230708_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employment_history',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects_portfolio',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='cover-letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'zip']), projects.models.Profile.validate_file_name_length, projects.models.Profile.max_file_size_ten]),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_resume',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'zip']), projects.models.Profile.validate_file_name_length, projects.models.Profile.max_file_size_ten]),
        ),
    ]
