# Generated by Django 3.2.18 on 2023-07-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0117_rename_privacy_profile_global_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='industry',
            field=models.TextField(blank=True, max_length=42, null=True),
        ),
    ]
