# Generated by Django 3.2.18 on 2023-07-10 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0120_auto_20230708_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
